<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
  	<Content Update="appsettings.json">
  	  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
  	  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
  	</Content>
  </ItemGroup>
	
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeHelper\CodeHelper.csproj" />
    <ProjectReference Include="..\JsonStreamingParser\JsonStreamingParser.csproj" />
  </ItemGroup>

</Project>
